name: Python CI

on: [push]

env:
  PRODUCTION: 0
  DEBUG: 1
  TEST: 1

  MONGO_URL: ${{ secrets.MONGO_URL }}

jobs:
  code-style:
    name: Coding Style Checks
    runs-on: ubuntu-latest

    timeout-minutes: 20

    continue-on-error: true

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-env.txt

      - name: '`flake8` - error check'
        run: |
          flake8 . --config .flake8-error --benchmark

      - name: '`flake8` - style check'
        run: |
          flake8 . --config .flake8-style --benchmark

      - name: '`pydocstyle`'
        run: |
          pydocstyle --count

      - name: '`pylint`'
        run: |
          pylint

  ci-test:
    name: CI Tests
    runs-on: ubuntu-latest

    timeout-minutes: 20

    continue-on-error: true

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-env.txt

      - name: 'Run `pytest`'
        run: |
          pytest
