name: Python CI

on: [push]

env:
  PRODUCTION: 0
  DEBUG: 1
  TEST: 1

  MONGO_URL: 'mongodb://localhost:27017/'

  DIR_CHECK: 'controllers endpoints responses api.py env_var.py error.py main.py'

jobs:
  code-style:
    name: Coding Style Checks
    runs-on: ubuntu-latest

    timeout-minutes: 20

    continue-on-error: true

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: '`flake8` - error check'
        run: |
          flake8 $DIR_CHECK --config .flake8-error --benchmark

      - name: '`flake8` - style check'
        run: |
          flake8 $DIR_CHECK --config .flake8-style --benchmark

      - name: '`pydocstyle`'
        run: |
          pydocstyle $DIR_CHECK --count

      - name: '`pylint`'
        run: |
          pylint $DIR_CHECK

  ci-test:
    name: CI Tests
    runs-on: ubuntu-latest

    timeout-minutes: 20

    continue-on-error: true

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: 'Use Node.js 12.x'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: 'Start MongoDB 4.2'
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: '4.2'

      - name: 'Run `pytest`'
        run: |
          pytest
